/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/InventoryScreen` | `/InventoryScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SalesScreen` | `/SalesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/BackButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/Scanner`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useScanner`; params?: Router.UnknownInputParams; } | { pathname: `/modal/manual`; params?: Router.UnknownInputParams; } | { pathname: `/modal/register`; params?: Router.UnknownInputParams; } | { pathname: `/utils/formatDate`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/InventoryScreen` | `/InventoryScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SalesScreen` | `/SalesScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/components/BackButton`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Scanner`; params?: Router.UnknownOutputParams; } | { pathname: `/hooks/useScanner`; params?: Router.UnknownOutputParams; } | { pathname: `/modal/manual`; params?: Router.UnknownOutputParams; } | { pathname: `/modal/register`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/formatDate`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/HomeScreen${`?${string}` | `#${string}` | ''}` | `/HomeScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/InventoryScreen${`?${string}` | `#${string}` | ''}` | `/InventoryScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SalesScreen${`?${string}` | `#${string}` | ''}` | `/SalesScreen${`?${string}` | `#${string}` | ''}` | `/components/BackButton${`?${string}` | `#${string}` | ''}` | `/components/Scanner${`?${string}` | `#${string}` | ''}` | `/hooks/useScanner${`?${string}` | `#${string}` | ''}` | `/modal/manual${`?${string}` | `#${string}` | ''}` | `/modal/register${`?${string}` | `#${string}` | ''}` | `/utils/formatDate${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HomeScreen` | `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/InventoryScreen` | `/InventoryScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SalesScreen` | `/SalesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/BackButton`; params?: Router.UnknownInputParams; } | { pathname: `/components/Scanner`; params?: Router.UnknownInputParams; } | { pathname: `/hooks/useScanner`; params?: Router.UnknownInputParams; } | { pathname: `/modal/manual`; params?: Router.UnknownInputParams; } | { pathname: `/modal/register`; params?: Router.UnknownInputParams; } | { pathname: `/utils/formatDate`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
